name: Test Scpt
applescript call:
  file: Test.scpt  
  handler: oi
  parameters: [text, option bbB]
after: show-result
options: 
- identifier: aaa
  type: string
  label: String Param
  defaultValue: abc123
- identifier: bbB
  type: boolean
  label: Booelan Param
  defaultValue: true