popclip version: 3785
name: Bitly
icon: bitly-logo.svg
identifier: com.pilotmoon.popclip.extension.bitly
entitlements: [network]
requirements: [url]
after: paste-result
module: bitly.js
description: Shorten the selected URL using Bitly.
app:
  name: Bitly
  link: http://bitly.com/ 